### ISSUE TITLE
Can't show Camera and Library button in fusumaVC

### ISSUE THREAD

**Issue by b-i-hide** [ytakzk/Fusuma#203] opened 2017-08-21 06:30 UTC
I use fusuma to choose an image and take a photo.
I set 'availableModes = [.library, .camera]'.
When I open fusumaVC,  I can't find Library button and Camera button.  These buttons are working, just not shown.
Is it a bug?? I can't find any solutions. If you have any solution, please help me.

**Comment by b-i-hide** [comment] 2017-08-21 06:40
<img width="380" alt="hh" src="https://user-images.githubusercontent.com/16622395/29506511-f65026c4-8686-11e7-9ae7-f0967ee1e256.png">

**Comment by ytakzk** [comment] 2017-08-28 15:13
@b-i-hide I cannot reproduce it. Do you replace all the strings on purpose because I cannot confirm the label of Photo on the top bar on the screen you shared?

**Comment by ytakzk** [comment] 2017-09-06 08:35
Close this issue until I receive the reproduction procedure.

**Closed as completed by ytakzk** 2017-09-06 08:35 UTC
